### ISSUE TITLE
Not able to drag inside an empty node

### ISSUE THREAD

**Issue by mehtaakshay2206** [angular-ui-tree/angular-ui-tree#688]
I am not able to drag anything inside a node which is empty. If the node has atleast another node, then the dragging works fine but if a node is empty, it never allows me to drop anything inside it.

**Comment by mehtaakshay2206** [comment]
I also see this issue on the demo page provided http://angular-ui-tree.github.io/angular-ui-tree/#/basic-example

For eg if I want to drop a Node 3.1 inside Node 2.2 , I am not able to do it.

Let me know if you need any further details.

Regards,
Akshay

**Comment by zibrohimov** [comment]
I've the same issue.

**Comment by zajhbuni** [comment]
if anyone has any pointers on how to fix this, would be great.

**Comment by nishantsamant** [comment]
I have the same issue..Can anyone help to fix this issue?

**Comment by pzagor2** [comment]
@mehtaakshay2206 I can drag node 3.1 inside 2.2, just move the mouse a little bit to the right.

**Comment by zachlysobey** [comment]
As a point of interest, I can also drag into 2.2, as described by @pzagor2.

Its possible this is a X-brower issue, or perhaps just user error.

This works for me on Chrome/OSX

**Comment by zajhbuni** [comment]
ahhhh. ok one wouldn't know it needs a bit of implied indentation to make it do that :) 
so not so much a user error, more a documentation thing? 
thanks all.

**Comment by blackat** [comment]
Hi,
@zachlysobey I have tested on the Basic Example both Chrome OSsX and Windows but it does not work, I have evn tried to use the trick proposed by @pzagor2 moving the mouse a little bit on the right but the node 3.1 goes or up or down the node 2.2.

Should I expect the node 2.2 gets a collapse/expand symbol with node 3.1 inside?

Help is really much appreciated :wink:

**Comment by zachlysobey** [comment]
It was trickier to get working with the plnkr (no placeholders, etc...), but it did work for me.

![screen shot 2016-02-10 at 10 53 01 am](https://cloud.githubusercontent.com/assets/1310403/12952434/749e5448-cfe4-11e5-850a-6f83327a3fa3.png)

On the basic example. After dragging 3.1 node to be a child of 2.2 I do see the expand/collapse icon. Nodes without any children themselves do not get this icon.

I have to say I'm pretty confused about what the issue is for you. Might be something better demonstrated with a video or screen-sharing?

**Comment by blackat** [comment]
Hi,
I have recorded a small [video](http://screencast-o-matic.com/watch/cDnXQ9hSF2) to show what happens. I have played on your website using Chrome browser on Windows 7 and I am not able to get it work, may be I am doing something not totally correct.

Yesterday I was doing it on Chrome for OSX and I got the exact same issue.

Thanks a lot @zachlysobey and @pzagor2 for the help :wink:

**Comment by zajhbuni** [comment]
Hey blackat drag the node 3.1 to under 2.1 - drop it. Then grab it and just pull it right - as if you wanted to indent it.

**Comment by pzagor2** [comment]
@blackat I know what you are talking about. I just implemented this into our product and QA team had the same problem as you. You have to drop item quite far to the right to get it into child group.

I think at 0:23 you even got the right drop zone highlighted. 

I wonder if there is an easy way to change it so that you can drop it on top of the node and this would make it go into the child group?

**Comment by blackat** [comment]
Sorry man but I do not see any drop zone highlighted :wink:

**Comment by nishantsamant** [comment]
@All : Actually I am still facing the issue. Help ASAP will be appreciated.

**Comment by acaron** [comment]
+1: Same issue

**Comment by acaron** [comment]
Solution here: https://github.com/angular-ui-tree/angular-ui-tree/issues/245 `children: []` is mandatory. That was my problem!

**Comment by blackat** [comment]
@acaron thanks a lot for the hint, I will try asap :wink:

**Comment by jacobscarter** [comment]
Closing this issue due to inactivity. See #815 for more information.
Please create a new issue is this still occurs with the current version of the component.
